version: "3.8"

services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: "2.7.1"
        BUNDLER_VERSION: "2.1.4"
    image: hivebrite-backend-test:1.0.0
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - .:/hivebrite-backend-test:cached
      - bundle:/usr/local/bundle
      - rails_cache:/app/tmp/cache
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - BOOTSNAP_CACHE_DIR=/bundle/_bootsnap
      - WEB_CONCURRENCY=1

  runner:
    <<: *app
    command: /bin/bash
    ports:
      - "3000:3000"
      - "3002:3002"

  rails:
    <<: *app
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - "3000:3000"

volumes:
  bundle:
  rails_cache:
